### PR TITLE
Issue#request permission to work on our work and value section

### LINKED ISSUE #3: Request Permission to Work on "Our Work And Value" Section
I would like to request permission to work on the "Our Work And Value" section of the AC-Website-NextJs application. This section of the app plays a crucial role in showcasing our organization's achievements, mission, and values, and I believe I can contribute positively to its development and enhancement. I will like it to have the label of the Hacktober Fest

### PR DESCRIPTION
**Pull request by chendjou237**
## Description

Added the About Us section to the website.

## Changes Made

- Created a new component called `AboutUs.tsx` in the `components` directory.
- Added the necessary markup and styles to display the section.
- Imported the `AboutUs` component in the `app/page.tsx` file and added it to the page.

## Screenshots

[Add any relevant screenshots here]
image

image

## Checklist

- [x] Tested locally.
- [x] Follows the project's code style and conventions.
- [x] Pull request title is clear and descriptive.

### CODE REVIEW

**Comment by Pranshu1902** [comment]
@chendjou237 fix the merge conflicts

**Comment by shubhamm69** [comment]
@chendjou237 Great work, just few minor changes. 
- do not make a component of this page instead 
- shift this existing file AboutUs.tsx to route (Home)/Section2.tsx and render this in page.tsx by importing section 2 component. 😄

**Review by shubhamm69 — CHANGES_REQUESTED** [review]
also do not import the font like this, we are using next/font. 
keep the svg inside a folder maybe assets/about,

**Comment by Pranshu1902** [comment]
@chendjou237 any updates?

**Pull request closed without merging**
